name: tintin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  faker: ^2.1.0
  provider: ^6.1.2
  sqflite: ^2.4.0
  path: ^1.9.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  location: ^7.0.1
  flutter_map_marker_popup: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - data/albums-tintin.json
    - images/
